name: Check-in tests

on:
  push:
    branches:
      - 'main'
      - 'releases-**'
  pull_request:
  workflow_dispatch:

env:
 BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
 EXCLUDE_ENTERPRISE: true

jobs:

  ci-ubuntu-server:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        db:
          - sqlite
          - mysql
          - mariadb
          - postgres

    steps:
    - name: Checkout
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

    - name: Set up Go
      uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e
      with:
        go-version-file: server/go.mod

    - name: "Test server: ${{matrix['db']}}"
      run: make server-test-${{matrix['db']}}

  ci-ubuntu-webapp:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      with:
        path: "focalboard"
        
    - name: npm ci
      run: cd focalboard/webapp && npm ci && cd -

    - name: Set up Go
      uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e
      with:
        go-version-file: focalboard/server/go.mod

    - name: Setup Node
      uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020
      with:
        node-version-file: focalboard/webapp/.nvmrc

    - name: Build Linux server
      run: cd focalboard; make server-linux-package

    - name: Copy server binary for Cypress
      run: cp focalboard/bin/linux/focalboard-server focalboard/bin/

    - name: Upload server package
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
      with:
        name: focalboard-server-linux-amd64.tar.gz
        path: ${{ github.workspace }}/focalboard/dist/focalboard-server-linux-amd64.tar.gz

    - name: Lint & test webapp
      run: cd focalboard; make webapp-ci

  ci-windows-server:
    runs-on: windows-2022

    strategy:
      matrix:
        db:
          - sqlite

    steps:
    - name: Checkout
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      with:
        path: "focalboard"

    - name: Set up Go
      uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e
      with:
        go-version-file: focalboard/server/go.mod

    - name: "Test server (minimum): ${{matrix['db']}}"
      run: cd focalboard; make server-test-mini-${{matrix['db']}}

  ci-mac-server:
    runs-on: macos-15

    strategy:
      matrix:
        db:
          - sqlite

    steps:
    - name: Checkout
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      with:
        path: "focalboard"

    - name: Set up Go
      uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e
      with:
        go-version-file: focalboard/server/go.mod

    - name: "Test server (minimum): ${{matrix['db']}}"
      run: cd focalboard; make server-test-mini-${{matrix['db']}}
